{% set name = "murex" %}
{% set version = "6.4.2063" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lmorg/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e980fdb8d822bf9ad8f26aa412b2771bdf154561e2dba4c30cc040db19232dd2

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - murex -v

about:
  home: https://murex.rocks
  license: GPL-2.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Bash-like shell designed for greater command-line productivity and safer scripts
  dev_url: https://github.com/lmorg/murex

extra:
  recipe-maintainers:
    - danielnachun
