{% set name = "murex" %}
{% set version = "7.1.4143" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lmorg/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f3620e00dc431ce202216c935d8e509cf0fdf0dd1e363eee9ec6cb64b0b182f4

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - murex -v

about:
  home: https://murex.rocks
  license: GPL-2.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Bash-like shell designed for greater command-line productivity and safer scripts
  dev_url: https://github.com/lmorg/murex

extra:
  recipe-maintainers:
    - danielnachun
