schema_version: 1

context:
  version: "7.2.0079"

package:
  name: murex
  version: ${{ version }}

source:
  url: https://github.com/lmorg/murex/archive/v${{ version }}.tar.gz
  sha256: 9f2c70496e9c465ecfa86d74b86e8c4489354ef755f130a775f02851b846c15f

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - murex -v

about:
  license: GPL-2.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Bash-like shell designed for greater command-line productivity and safer scripts
  homepage: https://murex.rocks
  repository: https://github.com/lmorg/murex

extra:
  recipe-maintainers:
    - danielnachun
